config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  get '/mypage', to: 'mypage#index'
  devise_for :users
  resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :tag_articles, dependent: :destroy
  has_many :tags, through: :tag_articles

  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true
  validates :tag_articles, presence: true
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_articles, dependent: :destroy
  has_many :articles, through: :tag_articles
end

app/models/tag_article.rb
class TagArticle < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[ index show ]
  before_action :set_article, only: %i[ edit update destroy ]

  # GET /articles
  def index
    articles = Article.all.includes(:tags)

    if params[:title].present?
      articles = articles.where("title LIKE ?", "%#{params[:title]}%")
    end

    @articles = articles.page params[:page]
  end

  # GET /articles/1
  def show
    @article = Article.find(params[:id])
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  def create
    @article = current_user.articles.new(article_params)
    if @article.save
      redirect_to @article, notice: "Article was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to @article, notice: "Article was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    edirect_to articles_url, notice: "Article was successfully destroyed."
  end

  private
    def set_article
      @article = current_user.articles.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :content, tag_ids:[])
    end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  # GET /mypage
  def index
    articles = current_user.articles.includes(:tags)

    if params[:title].present?
      articles = articles.where("title LIKE ?", "%#{params[:title]}%")
    end

    @articles = articles.page params[:page]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.collection_check_boxes :tag_ids, Tag.all, :id, :name %>
  </div>

  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :content, class: "form-label" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit '保存', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>
<%= form_with url: articles_url, method: :get, local: true do |form| %>
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="mb-3">
        <%= form.label :title, class: "form-label" %>
        <%= form.text_field :title, value: params[:title], class: "form-control" %>
      </div>
      <div class="actions">
        <%= form.submit '検索', class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>
<%= paginate @articles %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">タイトル</th>
      <th scope="col">内容</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td>
          <%= article.title %>
          <% article.tags.each do |tag| %>
            <span class="badge rounded-pill bg-primary"><%= tag.name%></span>
          <% end %>
        </td>
        <td><%= article.content %></td>
        <td>
          <%= link_to 'Show', article, class: "btn btn-success" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <div class="card-header">
    <%= @article.title %>
    <% @article.tags.each do |tag| %>
      <span class="badge rounded-pill bg-primary"><%= tag.name%></span>
    <% end %>
  </div>
  <div class="card-body">
    <%= @article.content %>
  </div>
</div>
<%= link_to 'Edit', edit_article_path(@article), class: "btn btn-warning" %>
<%= link_to 'Back', articles_path, class: "btn btn-secondary" %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "TOP", root_path, class: "navbar-brand" %>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if user_signed_in?%>
          <li class="nav-item">
            <%= link_to "マイページ", mypage_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link active" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "サインアップ", new_user_registration_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "サインイン", new_user_session_path, class: "nav-link active" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WonderfulPostApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/memos/_form.html.erb
<%= form_with(model: memo, local: true) do |form| %>
  <% if memo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(memo.errors.count, "error") %> prohibited this memo from being saved:</h2>

      <ul>
        <% memo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :content, class: "form-label" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit '保存', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/memos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Memos</h1>
<%= form_with url: memos_url, method: :get, local: true do |form| %>
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="mb-3">
        <%= form.label :title, class: "form-label" %>
        <%= form.text_field :title, value: params[:title], class: "form-control" %>
      </div>
      <div class="actions">
        <%= form.submit '検索', class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>
<%= paginate @memos %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">タイトル</th>
      <th scope="col">内容</th>
    </tr>
  </thead>
  <tbody>
    <% @memos.each do |memo| %>
      <tr>
        <td><%= memo.title %></td>
        <td><%= memo.content %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/mypage/index.html.erb
<p id="notice"><%= notice %></p>

<h1>マイページ</h1>

<%= form_with url: mypage_url, method: :get, local: true do |form| %>
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="mb-3">
        <%= form.label :title, class: "form-label" %>
        <%= form.text_field :title, value: params[:title], class: "form-control" %>
      </div>
      <div class="actions">
        <%= form.submit '検索', class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

<%= paginate @articles %>
<%= link_to 'New Article', new_article_path, class: "btn btn-info" %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">タイトル</th>
      <th scope="col">内容</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td>
          <%= article.title %>
          <% article.tags.each do |tag| %>
            <span class="badge rounded-pill bg-primary"><%= tag.name%></span>
          <% end %>
        </td>
        <td><%= article.content %></td>
        <td>
          <%= link_to 'Show', article, class: "btn btn-success" %>
          <%= link_to 'Edit', edit_article_path(article), class: "btn btn-warning" %>
          <%= link_to 'Destroy', article, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>